Repository VerzatileDevOrg/Programming_HandBook, pull requests merged in 2023-12, with the labels that each got.

#2 Add additional "IDE" category and templates to handbook
  docs/IDE/Notepad++/Notepad++.md
  docs/IDE/VisualStudioCode/VisualStudioCode.md
Labels: documentation

#3 Rename/Move VisualStudioCode -> VSCode
  docs/IDE/VSCode/VSCode.md
  docs/IDE/VisualStudio/VisualStudio.md
  docs/Language/C#/C#.md
  docs/Language/C++/C++.md
  docs/Language/C/C.md
  docs/Language/CSS/CSS.md
  docs/Language/HTML/HTML.md
  docs/Language/Haxe/Haxe.md
  docs/Language/JS/JS.md
  docs/Language/Lua/Lua.md
  docs/Language/Python/Python.md
  docs/Language/Ruby/Ruby.md
Labels: documentation

#4 Add Stubs for Framework + Engine
  docs/Engine/GameMakerStudio/GameMakerStudio.md
  docs/Engine/Godot/Godot.md
  docs/Engine/Unity/Unity.md
  docs/Engine/UnrealEngine/UnrealEngine.md
  docs/Framework/.NET/.NET.md
  docs/Framework/DirectX/DirectX.md
  docs/Framework/JUCE/JUCE.md
  docs/Framework/OpenGL/OpenGL.md
  docs/Framework/SFML/SFML.md
  docs/Language/GO/GO.md
  docs/Language/Java/Java.md
  docs/Language/Lisp/Lisp.md
  docs/Language/React/React.md
Labels: documentation

#7 Create new favicon
  favicon.ico
Labels: enhancement

#11 Add Page Content: SOLID
  docs/Concepts/SOLID.md
Labels: documentation

#13 Update Readme
  .github/workflows/ci.yml
  .github/workflows/jekyll.yml
  .github/workflows/pages.yml
  README.md
Labels: Documentation, Cosmetic

#15 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  Gemfile.lock
Labels: Documentation

#20 ADDED: Flutter framework markdown file
  docs/Framework/Flutter/Flutter.md
Labels: Documentation, Feature

#19 Add Sommos as contributor.md
  README.md
Labels: Documentation, Cosmetic

#21 ADDED: Profile Pictures For Contributors in README
  README.md
Labels: Documentation, Cosmetic

#23 [FIX] Web Build Error (Dependency Issue)
  .github/workflows/ci.yml
Labels: Bug: Major

#22 ADDED: Basic Outline For Algorithms
  docs/Concepts/Algorithms.md
  docs/Language/Dart/Dart.md
Labels: Content

#26 ADDED: Rust Language Outline
  docs/Language/Rust/Rust.md
Labels: Content, Review: Approved

#27 Remove whitespace
  .github/workflows/ci.yml
Labels: Bug: Major, CI, Review: Required

#30 Updating Index.md
  index.md
Labels: Content, Review: Required

#35 Correct Python content to Rust content.
  docs/Language/Rust/Rust.md
Labels: Content

#36 ADDED: Dark Theme
  _sass/custom/custom.scss
Labels: Cosmetic, Feature, Review: Approved

#38 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/content-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Feature, Review: Approved

#41 [ADD] Back To Top (B), SINCE: Date
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/components/footer.html
Labels: Cosmetic, Feature, CI, Review: Approved

#42 [FIX] Addressed Child in Child
  docs/Language/C++/C++.md
  docs/Language/C++/Pointers.md
Labels: Content, Cosmetic, Feature, Review: Approved

#43 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Type: Content, Review: Approved

#51 Fix date time modification
  .github/workflows/jekyll.yml
  .github/workflows/pages.yml
  _includes/components/footer.html
  docs/Concepts/Algorithms.md
  docs/Concepts/SOLID.md
  docs/Framework/Flutter/Flutter.md
  docs/Language/Dart/Dart.md
  docs/Language/Rust/Rust.md
Labels: Type: Feature, Review: Required

#52 Add Content: Pointers
  docs/Language/C++/Pointers.md
Labels: Type: Content, Review: Approved

#54 Remove int* typo
  docs/Language/C++/Pointers.md
Labels: Type: Content, Review: Required

#55 Create 404.html
  404.html
Labels: Type: Content, Type: Feature, Review: Approved

#57 Update Pointers.md
  docs/Language/C++/Pointers.md
Labels: Type: Content, Review: Approved

#59 ContentVisualStudioAndGithub
  docs/IDE/VisualStudio/ChangeProjectName.md
  docs/IDE/VisualStudio/VisualStudio.md
  docs/VersionControl/Git/Github.md
  docs/VersionControl/Git/Github/EnterpriseToPersonal.md
  images/VisualStudioImages/CopyOldFilterToNewFilter.png
  images/VisualStudioImages/OpenFolderInFileExplorer.png
  images/VisualStudioImages/ProjectFilters.png
  images/VisualStudioImages/ProjectFolderFilters.png
  images/VisualStudioImages/RescanSolution.png
  images/VisualStudioImages/SLNFile.png
  images/VisualStudioImages/SolutionDirectory.png
  images/VisualStudioImages/vcxprojFile.png
Labels: Type: Content, Review: Approved

#58 [CHANGE] Sidebar, Footer, search
  _includes/components/footer.html
  _includes/components/search_header.html
  _includes/components/sidebar.html
Labels: Type: Cosmetic, Review: Approved

#56 Added a use case quote citation and example
  _sass/custom/custom.scss
  docs/Language/C++/Addresses.md
  docs/Language/C++/ConstantPointerToConstant.md
  docs/Language/C++/ConstantPointers.md
  docs/Language/C++/Dereferencing.md
  docs/Language/C++/MemberPointers.md
  docs/Language/C++/MultilevelPointers.md
  docs/Language/C++/NullPointers.md
  docs/Language/C++/PointerToConstant.md
  docs/Language/C++/Pointers.md
  docs/Language/C++/RawPointers.md
  docs/Language/C++/References.md
  docs/Language/C++/SmartPointers.md
  docs/Language/C++/VoidPointers.md
Labels: Type: Content, Review: Approved

#60 Fix for some styling issues in Pointers docs
  docs/Language/C++/Addresses.md
  docs/Language/C++/ConstantPointerToConstant.md
  docs/Language/C++/ConstantPointers.md
  docs/Language/C++/Dereferencing.md
  docs/Language/C++/MemberPointers.md
  docs/Language/C++/MultilevelPointers.md
  docs/Language/C++/NullPointers.md
  docs/Language/C++/PointerToConstant.md
  docs/Language/C++/Pointers.md
  docs/Language/C++/References.md
  docs/Language/C++/VoidPointers.md
Labels: Type: Content, Review: Required

#63 Collections, Content Fixes, Removal of Un-used Code, Code.scss
  _sass/code.scss
  _sass/custom/collections.scss
  _sass/custom/custom.scss
  docs/Language/C++/Addresses.md
  docs/Language/C++/C++.md
  docs/Language/C++/ConstantPointerToConstant.md
  docs/Language/C++/ConstantPointers.md
  docs/Language/C++/Dereferencing.md
  docs/Language/C++/MemberPointers.md
  docs/Language/C++/MultilevelPointers.md
  docs/Language/C++/NullPointers.md
  docs/Language/C++/PointerToConstant.md
  docs/Language/C++/Pointers.md
  docs/Language/C++/RawPointers.md
  docs/Language/C++/References.md
  docs/Language/C++/SmartPointers.md
  docs/Language/C++/VoidPointers.md
Labels: Type: Content, Type: Cosmetic, Type: Feature, Review: Required, Priority: Minor

#64 Added C# content.
  docs/Language/C#/C#.md
Labels: Type: Content, Review: Required

#66 Added Python content
  docs/Language/Python/Python.md
Labels: Type: Content, Review: Approved

#67 Added Tries Content
  docs/Language/Python/Python.md
  docs/Language/Python/Tries.md
Labels: Type: Content, Review: Approved
