Repository VerzatileDevOrg/Programming_HandBook, pull requests merged in 2024-07, with the labels that each got.

#105 Add OOP Content
  docs/Concepts/OOP/OOP.md
Labels: 📖 Type: Content, ✅ Review: Approved

#106 Add Inheritance Content
  docs/Concepts/Inheritance/Inheritance.md
  docs/Concepts/OOP/OOP.md
  docs/Concepts/Polymorphism/Polymorphism.md
Labels: 📖 Type: Content, 👁️ Review: Required

#107 Release V.1.0.0
  _config.yml
  docs/Concepts/Inheritance/Inheritance.md
  docs/Concepts/OOP/OOP.md
  docs/Concepts/Polymorphism/Polymorphism.md
  docs/IDE/Notepad++/Notepad++.md
Labels: 📖 Type: Content, 🌟 Type: Feature, 👁️ Review: Required

#111 Permalink,, #108, #61, #109 Fixes - Changes
  docs/Concepts/Algorithms/index.md
  docs/Concepts/DevOps/index.md
  docs/Concepts/ECS/index.md
  docs/Concepts/Inheritance/index.md
  docs/Concepts/Memory/index.md
  docs/Concepts/OOP/index.md
  docs/Concepts/Polymorphism/index.md
  docs/Concepts/SOLID/index.md
  docs/Concepts/index.md
  docs/Engine/GameMakerStudio/index.md
  docs/Engine/Godot/index.md
  docs/Engine/Unity/index.md
  docs/Engine/UnrealEngine/index.md
  docs/Engine/index.md
  docs/Framework/DirectX/index.md
  docs/Framework/Flutter/index.md
  docs/Framework/JUCE/index.md
  docs/Framework/NET/index.md
  docs/Framework/OpenGL/index.md
  docs/Framework/SFML/index.md
  docs/Framework/index.md
  docs/IDE/AdobeDreamWeaver/index.md
  docs/IDE/MonoDevelop/index.md
  docs/IDE/NetBeans/index.md
  docs/IDE/Notepad++/index.md
  docs/IDE/Rider/index.md
  docs/IDE/VSCode/index.md
  docs/IDE/VisualStudio/index.md
  docs/IDE/index.md
  docs/Language/C#/index.md
  docs/Language/C++/index.md
  docs/Language/C/index.md
  docs/Language/CSS/index.md
  docs/Language/Dart/index.md
  docs/Language/GO/index.md
  docs/Language/HTML/index.md
  docs/Language/Haxe/index.md
  docs/Language/JS/index.md
  docs/Language/Java/index.md
  docs/Language/Lisp/index.md
  docs/Language/Lua/index.md
  docs/Language/Python/index.md
  docs/Language/React/index.md
  docs/Language/Ruby/index.md
  docs/Language/Rust/index.md
  docs/Language/index.md
  docs/VersionControl/Git/GitBash.md
  docs/VersionControl/Git/Github.md
  docs/VersionControl/Git/Github/EnterpriseToPersonal.md
  docs/VersionControl/Git/Github/index.md
  docs/VersionControl/Git/Gitlab.md
  docs/VersionControl/Git/index.md
  docs/VersionControl/P4V/Helix.md
  docs/VersionControl/P4V/HelixSwarm.md
  docs/VersionControl/P4V/Perforce.md
  docs/VersionControl/P4V/index.md
  docs/VersionControl/PlasticSCM/index.md
  docs/VersionControl/index.md
Labels: 🌈 Type: Cosmetic, ✅ Review: Approved

#113 Update to Just the Docs 0.8.0
  Gemfile
  Gemfile.lock
Labels: ✅ Review: Approved, 📦 Dependencies
