Repository VerzatileDevOrg/Programming_HandBook, pull requests merged in 2024-01, with the labels that each got.

#69 ADDED: DevOps Section To Concepts
  docs/Concepts/DevOps.md
Labels: Type: Content, Review: Required

#71 Organization content changes
  _includes/under_construction.html
  assets/images/VisualStudioImages/CopyOldFilterToNewFilter.png
  assets/images/VisualStudioImages/OpenFolderInFileExplorer.png
  assets/images/VisualStudioImages/ProjectFilters.png
  assets/images/VisualStudioImages/ProjectFolderFilters.png
  assets/images/VisualStudioImages/RescanSolution.png
  assets/images/VisualStudioImages/SLNFile.png
  assets/images/VisualStudioImages/SolutionDirectory.png
  assets/images/VisualStudioImages/vcxprojFile.png
  assets/images/under_construction.png
  docs/IDE/VisualStudio/ChangeProjectName.md
Labels: Type: Content, Type: Cosmetic, Review: Required

#68 Language specific examples
  _layouts/default.html
  assets/js/programmingLanguageSwitch.js
  docs/Concepts/Memory.md
  docs/Concepts/OOP.md
Labels: Type: Content, Type: Cosmetic, Type: Feature, Review: Approved, Priority: Minor

#75 Interface updates (Default Theme)
  _config.yml
  _includes/components/footer.html
  _includes/under_construction.html
  _layouts/default.html
  _sass/code.scss
  _sass/custom/collections.scss
  _sass/custom/custom.scss
  docs/Language/C++/Addresses.md
  docs/Language/C++/C++.md
  docs/Language/C++/ConstantPointerToConstant.md
  docs/Language/C++/ConstantPointers.md
  docs/Language/C++/Dereferencing.md
  docs/Language/C++/MemberPointers.md
  docs/Language/C++/MultilevelPointers.md
  docs/Language/C++/NullPointers.md
  docs/Language/C++/PointerToConstant.md
  docs/Language/C++/Pointers.md
  docs/Language/C++/RawPointers.md
  docs/Language/C++/References.md
  docs/Language/C++/SmartPointers.md
  docs/Language/C++/VoidPointers.md
  index.md
Labels: 🌈 Type: Cosmetic, 👁️ Review: Required
