Repository VerzatileDevOrg/Programming_HandBook, pull requests merged in 2024-06, with the labels that each got.

#96 Addressing base information sections
  docs/Concepts/Algorithms/Algorithms.md
  docs/Concepts/Concepts.md
  docs/Concepts/DevOps/DevOps.md
  docs/Concepts/ECS/ECS.md
  docs/Concepts/Inheritance/Inheritance.md
  docs/Concepts/Memory/Memory.md
  docs/Concepts/OOP/OOP.md
  docs/Concepts/Polymorphism/Polymorphism.md
  docs/Concepts/SOLID/SOLID.md
  docs/Engine/Engine.md
  docs/Framework/Framework.md
  docs/IDE/IDE.md
  docs/Language/Language.md
  docs/VersionControl/VersionControl.md
Labels: 📖 Type: Content, ✅ Review: Approved

#102 Fix a permalik suffix to remove .html
  _config.yml
Labels: 🌈 Type: Cosmetic, 👁️ Review: Required

#103 Add content for Notepad++
  docs/IDE/Notepad++/Notepad++.md
Labels: 📖 Type: Content, 👁️ Review: Required
